.TH SkyTG24 1
.SH NAME
.B skytg24
- un semplice client per Sky TG24

.SH DESCRIPTION
Una semplice applicazione che permette la visione di 
.B SkyTG24
senza l'utilizzo di un browser dedicato.
    
Lo stream è trasmesso all'indirizzo:
.I http://tg24.sky.it/tg24/diretta.html
  
.SH AUTHOR
Leo Iannacone <l3on@ubuntu.com>

.SH COPYRIGHT
Copyright   ©   2013   Leo Iannacone
    http://leoiannacone.com

License   GPLv3+:   GNU  GPL  version  3  or  later
   <http://gnu.org/licenses/gpl.html>.
